### ISSUE TITLE
D2 PRODUCTION: ERROR: 415 -- 415 Unsupported Media Type

### ISSUE THREAD

**Issue by szanati** [fcla/xmlresolution#35]
I got this error on 2 packages It is similar to: https://github.com/daitss/core/issues/472?source=cc.

Fri Nov 01 16:05:55 -0400 2013
415 -- 415 Unsupported Media Type - #<REXML::ParseException: Declarations can only occur in the doctype declaration.
Line: 
Position: 
Last 80 unconsumed characters:
<! Style Sheet Definitions > <style>    .logFileName { font-size: 20pt; text-alig>
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/parsers/baseparser.rb:344:in `pull'
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/parsers/treeparser.rb:22:in`parse'
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/document.rb:205:in `build'
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/document.rb:42:in`initialize'
/opt/web-services/sites/xmlresolution/releases/20121126174628/lib/xmlresolution/xml_resolver.rb:186:in `new'
/opt/web-services/sites/xmlresolution/releases/20121126174628/lib/xmlresolution/xml_resolver.rb:186:in`initialize'
./lib/app/posts.rb:26:in `new'
./lib/app/posts.rb:26:in`POST /ieids/:collection_id/'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1151:in `call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1151:in`compile!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:724:in `instance_eval'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:724:in`route_eval'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:708:in `route!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:758:in`process_route'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:755:in `catch'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:755:in`process_route'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:707:in `route!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:706:in`each'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:706:in `route!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:843:in`dispatch!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in `call!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in`instance_eval'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in `invoke'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in`catch'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in `invoke'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in`call!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:629:in `call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in`call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1272:in `call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1303:in`synchronize'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1272:in `call'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/request_handler.rb:96:in`process_request'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:205:in `start_request_handler'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:170:in`send'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:170:in `handle_spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/utils.rb:479:in`safe_fork'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:165:in `handle_spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in`**send**'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:180:in `start'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:128:in`start'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rack_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:246:in `spawn_rack_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:82:in`synchronize'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:244:in`spawn_rack_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/opt/ruby/gem-repos/gems/passenger-3.0.7/helper-scripts/passenger-spawn-server:99
...
Declarations can only occur in the doctype declaration.
Line: 
Position: 
Last 80 unconsumed characters:
<! Style Sheet Definitions > <style>    .logFileName { font-size: 20pt; text-alig
Line: 
Position: 
Last 80 unconsumed characters:
<! Style Sheet Definitions > <style>    .logFileName { font-size: 20pt; text-alig   document uri: file://fclnx30.fcla.edu/EELMC4211_5GLNV6/QC_Error.html.
http://xmlresolution.fda.fcla.edu/ieids/EELMC4211_5GLNV6/: 415
415 Unsupported Media Type - #<REXML::ParseException: Declarations can only occur in the doctype declaration.
Line: 
Position: 
Last 80 unconsumed characters:
<! Style Sheet Definitions > <style>    .logFileName { font-size: 20pt; text-alig>
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/parsers/baseparser.rb:344:in`pull'
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/parsers/treeparser.rb:22:in `parse'
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/document.rb:205:in`build'
/opt/ruby-1.8.7/lib/ruby/1.8/rexml/document.rb:42:in `initialize'
/opt/web-services/sites/xmlresolution/releases/20121126174628/lib/xmlresolution/xml_resolver.rb:186:in`new'
/opt/web-services/sites/xmlresolution/releases/20121126174628/lib/xmlresolution/xml_resolver.rb:186:in `initialize'
./lib/app/posts.rb:26:in`new'
./lib/app/posts.rb:26:in `POST /ieids/:collection_id/'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1151:in`call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1151:in `compile!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:724:in`instance_eval'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:724:in `route_eval'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:708:in`route!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:758:in `process_route'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:755:in`catch'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:755:in `process_route'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:707:in`route!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:706:in `each'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:706:in`route!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:843:in `dispatch!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in`call!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in `instance_eval'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in`invoke'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in `catch'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:808:in`invoke'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:644:in `call!'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:629:in`call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in`call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1272:in`call'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1303:in `synchronize'
/opt/web-services/sites/xmlresolution/shared/bundle/ruby/1.8/gems/sinatra-1.2.6/lib/sinatra/base.rb:1272:in`call'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_request_handler.rb:513:in`accept_and_process_next_request'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:205:in`start_request_handler'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:170:in `send'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:170:in`handle_spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/utils.rb:479:in `safe_fork'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:165:in`handle_spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:180:in`start'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:253:in`spawn_rack_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:246:in`spawn_rack_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:137:in`spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in`**send**'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/opt/ruby/gem-repos/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
/opt/ruby/gem-repos/gems/passenger-3.0.7/helper-scripts/passenger-spawn-server:99
...
Declarations can only occur in the doctype declaration.
Line: 
Position: 
Last 80 unconsumed characters:
<! Style Sheet Definitions > <style>    .logFileName { font-size: 20pt; text-alig
Line: 
Position: 
Last 80 unconsumed characters:
<! Style Sheet Definitions > <style>    .logFileName { font-size: 20pt; text-alig   document uri: file://fclnx30.fcla.edu/EELMC4211_5GLNV6/QC_Error.html.

**Comment by szanati** [comment]
The 2 packages have been stashed in stashspace: GitHub_35

**Comment by jonpitts** [comment]
This issue seems to have been reintroduced by commit 799a8b4ceb8f58c6f895d6dda175ef4c757f65e1

This was previously fixed by 7b84a517ea64176a7aac4549a7dc63d6944cb8be

Specifically https://github.com/daitss/xmlresolution/blob/master/lib/xmlresolution/xml_resolver.rb#L188 throws the error seen above.
