### ISSUE TITLE
ripple: Fatal error premature end of data in tag html

### ISSUE THREAD

**Issue by lydiam** [fcla/xmlresolution#6]
SNAFU on ripple with the following error:

```
 02:40 pm
 message    Fatal error: Premature end of data in tag html line 2 at :18.
 stacktrace     

 /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.4/lib/libxml/document.rb:74:in `parse'
 /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.4/lib/libxml/document.rb:74:in `string'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/xmlresolve.rb:37:in `resolve_datafiles'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/xmlresolve.rb:35:in `each'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/xmlresolve.rb:35:in `resolve_datafiles'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/xmlresolve.rb:13:in `xmlresolve!'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/preserve.rb:26:in `preserve!'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/step.rb:14:in `step'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/step.rb:23:in `step!'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/step.rb:14:in `step'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/preserve.rb:26:in `preserve!'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/../lib/daitss/proc/wip/ingest.rb:23:in `ingest!'
 /var/daitss/services/core/lib/daitss/proc/wip/../../../../bin/dbin:20
```

The WIP is E000019N7_DVHA6X and the SIP name is UF00095774_00212.

**Comment by grf** [comment]
I do not believe this is an xmlresolution error.

**Comment by grf** [comment]
this is not an xmlresolution error. please reopen in core if it persists.
