### ISSUE TITLE
snafu: No route to host (2)

### ISSUE THREAD

**Issue by lydiam** [fcla/xmlresolution#9]
It looks like my packages today are SNAFU-ing at xmlresolution:

```
 Fri Dec 17 11:29:00 -0500 2010
```

message     No route to host - connect(2)
trace   

```
 /opt/ruby-1.8.7/lib/ruby/1.8/net/http.rb:560:in `initialize'
 /opt/ruby-1.8.7/lib/ruby/1.8/net/http.rb:560:in `open'
 /opt/ruby-1.8.7/lib/ruby/1.8/net/http.rb:560:in `connect'
 /opt/ruby-1.8.7/lib/ruby/1.8/timeout.rb:53:in `timeout'
 /opt/ruby-1.8.7/lib/ruby/1.8/timeout.rb:93:in `timeout'
 /opt/ruby-1.8.7/lib/ruby/1.8/net/http.rb:560:in `connect'
 /opt/ruby-1.8.7/lib/ruby/1.8/net/http.rb:553:in `do_start'
 /opt/ruby-1.8.7/lib/ruby/1.8/net/http.rb:542:in `start'
 /opt/ruby-1.8.7/lib/ruby/1.8/net/http.rb:440:in `start'
 /var/daitss/services/core/lib/daitss/proc/wip/xmlresolve.rb:22:in `put_collection_resource'
```

I ran "daitss start all", hoping that this error just meant that the resolution service wasn't running, but that didn't help.

How is the resolution service started?  I'm not sure how to troubleshoot this.

**Comment by grf** [comment]
firewall/config issue on ingest side - can't get to xmlresolution service
